version: '3'

services:
    web:
        image: aspendigital/octobercms
        ports:
            - 80:80
        volumes:
            - ./src/:/var/www/html/
        environment:
            - DB_TYPE=mysql
            - DB_HOST=mysql #DB_HOST should match the service name of the database container
            - DB_DATABASE=bwolf
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - MAIL_DRIVER=smtp
            - MAIL_HOST=maildev
            - MAIL_PORT=25

    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=bwolf

    maildev:
        image: djfarrelly/maildev
        ports:
            - 1080:80
            - 25:25
    algorithm:
        build: ./src/algorithm
        volumes:
            - ./src/algorithm/src:/usr/src/app/src/
        ports:
            - 1337:80
